title: O Novo Livro Digital
email: contato@onovolivro.digital
description: >
  Registro do processo de design de uma nova plataforma para criação
  e publicação colaborativa de web livros. É também por si só uma publicação
  digital e um local para experimentos web.
github_username:  onovolivro

markdown: kramdown